#!/bin/bash
apt update
#to install java
apt install default-jre -y
cd "/opt/"
echo "enter the specific tomcat version in 8, 9, 10 or 11"
read version
case $version in
        8)wget  https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.97/bin/apache-tomcat-8.5.97.tar.gz
                ;;
        9)wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.84/bin/apache-tomcat-9.0.84.tar.gz
                ;;
        10)wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz
                ;;
        11)wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.0-M15/bin/apache-tomcat-11.0.0-M15.tar.gz
                ;;
        *)echo "invalid input. Exiting script." && exit 1
		;;
esac
tarfile=$(ls -rt /opt/ | grep "tar.gz")
tar -xvzf $tarfile
apache=$(echo "$tarfile" | sed 's/.tar.gz//g')
sed -i 's/8080/8082/g' /opt/$apache/conf/server.xml
sed -i  '21s/^/<!--/g' "/opt/$apache/webapps/host-manager/META-INF/context.xml"
sed -i  '22s/$/-->/g' "/opt/$apache/webapps/host-manager/META-INF/context.xml"
sed -i  '21s/^/<!--/g' "/opt/$apache/webapps/manager/META-INF/context.xml"
sed -i  '22s/$/-->/g' "/opt/$apache/webapps/manager/META-INF/context.xml"
sed -i -e '55 a\<role rolename="manager-gui" /> \n<user username="tarun" password="99490" roles="manager-gui" /> \n<!-- user admin can access manager and admin section both --> \n<role rolename="admin-gui" /> \n<user username="tarun" password="99490" roles="manager-gui, admin-gui" />' "/opt/$apache/conf/tomcat-users.xml"
cd "/opt/$apache/bin/"
/opt/$apache/bin/shutdown.sh
/opt/$apache/bin/startup.sh
echo "use instance pub ip:8082 to check the tomcat server"
cd /home/ubuntu/ hello-world-war
git clone https://github.com/tarundanda147/hello-world-war.git
cd hello-world-war
sudo apt install maven
mvn clean install
cd target
cp hello-world-war-1.0.0.war /opt/$apache/webapps
/opt/$apache/bin/shutdown.sh
/opt/$apache/bin/startup.sh
